name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  docker-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and start services
        run: docker-compose up -d --build
      - name: Wait for app to finish
        run: |
          docker-compose logs -f food-data-loader &
          sleep 60 # Wait for the app to finish loading data
      - name: Run tests in container
        run: docker-compose run --rm food-data-loader sbt test
      - name: Run coverage in container
        run: docker-compose run --rm food-data-loader sbt coverage test coverageReport
      - name: Copy coverage report
        run: |
          docker cp $(docker-compose ps -q food-data-loader):/app/target/scala-2.13/scoverage-report/scoverage.xml ./scoverage.xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./scoverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
      - name: Cleanup
        if: always()
        run: docker-compose down -v 