version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: food_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  food-data-loader-test:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: food_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    command: ["sbt", "clean", "coverage", "test", "coverageReport"] 