version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: food_db
      POSTGRES_USER: food_user
      POSTGRES_PASSWORD: food_pass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "food_user"]
      interval: 10s
      timeout: 5s
      retries: 5
  food-data-loader:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: food_db
      DB_USERNAME: food_user
      DB_PASSWORD: food_pass
    command: ["sbt", "run"] 