name: Scala CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: food_db
          POSTGRES_USER: food_user
          POSTGRES_PASSWORD: food_pass
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: sbt
      
      - name: Cache SBT
        uses: actions/cache@v4
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt', '**/project/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-sbt-cache-v2-
      
      - name: Wait for PostgreSQL
        run: |
          while ! pg_isready -h localhost -p 5432 -U food_user -d food_db; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
      
      - name: Run tests
        run: sbt test
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: food_db
          DB_USERNAME: food_user
          DB_PASSWORD: food_pass
      
      - name: Run tests with coverage
        run: sbt coverage test coverageReport
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: food_db
          DB_USERNAME: food_user
          DB_PASSWORD: food_pass
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./target/scala-2.13/scoverage-report/scoverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true 